NetoECommerce/Skeletal

httpdocs/assets/themes/skeletal/css/app.css, httpdocs/assets/themes/skeletal/css/app.less
Initial problem is with the Add to Cart button icons not triggering the javascript function on-click, however this should be applicable to all icons within buttons.
=> Fix for iconography within buttons not triggering javascript functions

private/www/netosuite/Templates/skeletal/customer/edit_address/template.html
Seems something in **neto.js** is stopping us from testing the `select` element correctly. I suspect this is a jQuery compatibility thing...
=> Setting a default value for country for new addresses

private/www/netosuite/Templates/skeletal/products/template.html
The zoom plugin and jcountdown had their respective plugin scripts being loaded against the wrong blocks of code, which is unnecessarily confusing
=> loading plugins against correct init code blocks

private/www/netosuite/Templates/skeletal/thumbs/product/template.html
When using characters like '&' in the product name, when maxlength calculates, it calculates based on the encoded value for that character, cutting the resulting struct after 46 chars instead of 50
=> truemaxlength to account for HTML encoding

src/templates/customer/pay_order/pay_now_confirm.template.html
`[%payment_methods%]` has a new parameter which forces it to respect `[@amount_owed@]` for paying existing orders.
=> CORE-1615 - Update payment_methods function to respect amount owed

src/templates/products/includes/header.template.html
There was no structured data on the "Promotion" side of the promo conditional statement at all.
=> Adding structured data for promo_price to the product page header

src/templates/customer/nr_view_order/order.template.html
The pay button was showing regardless of full or partial payment on orders, it requires a show_order function for the ability to access the [@amount_owed@] data to validate this.
=> Logic for "pay" button on view order to check amount_owed

src/templates/thumbs/advert/carousel.template.html, src/templates/thumbs/advert/scroll.template.html, src/templates/thumbs/advert/text.template.html
The [@target@] tag doesn't have a database column to hold a value, nor any control panel UI to accept this value. It is always returning blank so we've redundantly got target="" on all advert templates that used this post-parsing.
=> Removing target="[@target@]" from Advert URLs

src/templates/cart/shopping_cart.template.html
- If `CHECKOUT_UPSELL_EXTRA` is true, you can [edit the gift messages from the cart item](http://design.neto.com.au/assets/uploads/https___imaginenoatheme_neto_com_au__mycart_tkn_cart_ts_1469679694725839_1D49C21A.png). Just links to the upsell page, which already has the extra options there ready to be edited. Makes [this tweak](https://www.neto.com.au/designer-documentation/tweak-library/cart-page/edit-gift-message-button/) redundant.
- Extra options are on their own line, outside of the `<h4>` which the cart item name is inside.
- Cleaned up the logic around the **Create Quote From Cart** button.
- Added a top-level "Edit extra options" button, but it's commented out by default.
=> Refinements to how extra options work on the cart

src/templates/cart/shopping_cart.template.html
Due to the way b@se handles whitespace, the value & readonly attributes where being concatenated incorrectly
=> Fixing readonly/value for fixed_assemble kits on the shopping cart

src/css/app.css, src/css/app.less
There was width: 60px applying to the .variation-name class unnecessarily and causing word wrap for basically any two-word specific names.
=> Fix for variation-name width limitation

src/templates/cms/includes/sidebar.template.html
The '$' was statically coded, this has now been modified to pull the currency symbol from the checkout
=> Inserting [@config:currency_symbol@] into the price filter JS

src/templates/headers/template.html
This change will cause logos to be purged when hitting save on the theme editor. Customers will be able to make sure all browsers see the new logo without needing a design tweak. Alternatively replace [@config:neto_css_version@] with a format function loading the date (only to the day) so that the logo is "purged" daily
=> Purging Logos

src/templates/products/includes/child_products.template.html
There is no label-important class, so the out of stock was displaying white text on a white background.
=> Fixed sold out label

src/templates/cms/includes/sidebar.template.html
There is no default brands page, so the 'show all brands' link in the sidebar will link to nowhere. I've removed this link and the brands output limit.
Until we have a brands page as standard install we will create a tweak doc to add this functionality back in with a manually created brands page.
=> Removed brands limit and show all link

src/templates/cart/shopping_cart.template.html
This is an extension to #218
Which was closed due to incorrect/unknown repository
```
When a product is added to the cart as a freebie, remove the qty input and the remove from cart button since these do not function for freebie products.
```
=> freebies shopping cart

src/templates/products/includes/images.template.html
Added CDN hosted `default_product.gif` as the default image on product page. This ensures a more consistent experience, showing the same default image that is shown on the thumbnail template.
=> Consistency for default product image on product page vs thumbnails.

src/templates/thumbs/product/list.template.html
Removed `.btn-block` class from Out Of Stock button on list view thumbnail to match styling of other buttons.
=> Match Out Of Stock button styling with other buttons on list view thumbnails

gulpfile.js, package-lock.json, src/css/app.css, src/css/less/_neto.less, src/css/less/_variables.less, src/css/less/app.less
As a theme developer, I want to use a LESS configuration that compiles all vendor and custom styles into one stylesheet.
Currently we have app.less that imports bootstrap, has Neto specific styles and a theme developer is expected to add their custom styles at the bottom of this file. This can lead to unexpected issues and can be intimidating for developers using this process for the first time.
This PR extracts app.less into three partials which all get imported into app.less, which in turn makes app.css
This imports all vendor code and any custom variables/mixins that might be used in custom.less
This includes all Neto specific code which is needed for a neto theme.
This is where all custom styles should be placed when developing a theme. by default, it is empty but is imported into …
=> Updated less to use partials

src/templates/footers/checkout.template.html, src/templates/footers/includes/scripts.template.html, src/templates/footers/template.html, src/templates/headers/checkout.template.html, src/templates/headers/empty.template.html, src/templates/headers/includes/head.template.html, src/templates/headers/template.html, src/templates/products/template.html
First-time Neto theme developers can be intimidated with the amount of necessary/required code in some templates and it can be very easy to accidentally remove some of this code and break the whole site.
It would be a good idea to place this code in an includes template so it is still apart of the template but developers do not have to worry about it. 
With theme depending off Skeletal, a benefit to this would be when a theme is built, it would pull the latest includes from skeletal so your theme would have the most up to date meta tags or maybe a script tag version if it ever gets updated in skeletal.
---
headers/includes/head - has all the head HTML
footers/includes/script - has all Neto necessary scripts, site_value, tracking_code, npopup, nactivity.
product/template.html - Moved …
=> Moved required code in header/footer into their own files

src/templates/cart/shopping_cart.template.html
These fields should be type `number` for better validation and also to show the numerical keyboard on mobile devices. 
Also they already have min/max attributes - these don't even work on inputs of type `text`
=> Changed cart QTY fields to type number

src/templates/customer/template.html
There was an issue where the orders thumb_list was limited by 10 orders but pagination only kicked in after 15 orders, meaning in some situations a customer may not be able to see their full order history. 
This PR fixes that issue 🎉🎉🎉
I've also changed the limit on the orders thumb_list to 9 so that it doesn't leave an outlier in the 3 column layout.
=> Fix issue where some orders may not be visible on my account page

src/templates/customer/template.html
- Fixed pagination on quotes section (previously it would just change the page of the orders section)
- Copied aria-labels and next/previous style from orders pagination section
- Up the limit on the quotes section to 10 as the table layout is pretty compact
- Remove duplicate footer param
=> Fix pagination of quotes on my account page

src/templates/cms/home.template.html
Update the opening line of the [%random_products %] tag to remove category:'0' and replace with filter_category:'' and reword the description surrounding the category parameter.
Current implementation does not display any random products when implemented on the home page.
Current code
[%random_products category:'0' template:'' limit:'8'%]
New Code
[%random_products filter_category:'' template:'' limit:'8' %]
=> Updating 'category:' to 'filter_category:'

src/templates/products/includes/buying_options.template.html
Added from customer feedback about shipping calculator allowing negative number. Will still allow if typed but stops the increment from going below zero on click
=> Min on shipping calculator

src/js/custom.js, src/templates/products/includes/buying_options.template.html, src/templates/products/includes/product_scripts.template.html
- Notify Me button would not display loading spinner when switching variations on the product page, even though the other button styles would
- When switching variations on the product page, all `.addtocart` classed buttons spin (including the buttons on product thumbs at the bottom of the page)
- Changed the `$('.addtocart').button("loading")` function to use a more specific class - `.btn-ajax-loads`
- Added loading animation to Notify Me button when switching variations
=> Notify Me button does not show loading animation on variation switch

src/templates/headers/includes/head.template.html, src/templates/headers/template.html
Potential solution to #401 
More info
https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content
without preload
with preload
=> Preload styles for modern browsers

src/js/custom.js, src/templates/cart/onepage.template.html, src/templates/customer/login.template.html, src/templates/customer/register/template.html, src/templates/customer/wholesaleregister/template.html, src/templates/footers/template.html, src/templates/products/includes/buying_options.template.html
GDPR ensures an organisation be able to justify each type of data processing activity it conducts, using one of six lawful bases of processing.
- An individual must have the opportunity to make an actual choice to provide consent. A pre-checked checkbox on a form does not qualify as consent under the GDPR, because it removes the affirmative action of giving consent. Individuals must check the box themselves to provide proper consent, or click on the confirmation link in an email to confirm that they are opting in to receive your marketing emails.
- The choice to provide consent must be clearly distinguishable and separate from other initiatives. This means individuals can’t be required to give consent as a condition for receiving a resource, product, or service.
Opting out of newsletter …
=> GDPR update

README.md, gulpfile.js, package.json
Nobody likes global dependencies.
=> Update build scripts to allow gulp as a local dependency

src/templates/cart/shopping_cart.template.html
In connection with CAT-115, the Paypal link on the cart page needs additional logic to check when to display based on user group.
CAT-115 is part of the epic `managed_checkout_V2`, which is being released in `6.18.0`, so this change should be merged in when `6.18.0` is released. Will require local environment to test.
=> New Paypal link implementation

src/js/custom.js
These images were probably used by wishlist popup interface in the past. Since they aren't anymore, the images are still being preloaded when they don't need to be. From a performance perspective this is negligible however since it loads after the dom renders it means its one more thing certain site performance checkers will treat as a false positive, potentially increasing the reported page load times.
=> Custom.js addToWishList params

src/templates/cms/includes/sidebar.template.html
This means that even if you mash the screen with your fat thumb the filters panel will still open. 
E.g. You just need to hit the panel, rather than the text itself.
=> Made "filter products" heading a block element

src/templates/cms/category.template.html, src/templates/products/template.html
BreadcrumbList is missing the position schema data. There was also a double up of the BreadcrumbList itemtype.
https://search.google.com/structured-data/testing-tool#url=http%3A%2F%2Fskeletaltheme.neto.com.au%2Fsample-product-1
=> Added missing position schema data

src/templates/products/includes/product_information.template.html
Accordion links should be block elements for ease of use.
=> Accordion links on product page are now block elements

src/scss/_neto.scss
This fix stops long select option names from causing iOS to side scroll on product pages.
=> iOS Select Option Overflow

src/templates/cms/default.template.html
At the moment, the Skeletal theme doesn't provide a way of nesting content pages which have a parent set on the page.
Have added ` show_next_level:'[@content_level@]' ` to enable this functionality. Has been tested in our theme at Jetblack Espresso and works well (see https://www.jetblackespresso.com.au/exploded-views/ for example)
=> Adding content level for nested content/content with a parent page

src/templates/products/includes/header.template.html
We get a lot of support cases where the condition microdata is missing for Google Shopping.
=> Add condition microdata

package-lock.json, package.json
Updated gulp-sass because a dependency was causing install issues.
Updated Bootstrap and Popper.js to not have a `^`, so they do not update automatically with `npm update`. Bootstrap/jQuery/Popper.js should be updated together as they are peer dependencies and the concatenated JS file is hosted on the CDN, so requires a little bit more work to update those dependencies.
=> updated package dependencies

src/templates/cms/default.template.html, src/templates/cms/products.template.html, src/templates/cms/search_results.template.html, src/templates/cms/store_finder.template.html
This new breadcrumb already existed on the category template and product template but didn't seem to be applied on other pages. This was giving schema data errors as can be seen here:  [https://search.google.com/structured-data/testing-tool/u/0/#url=http%3A%2F%2Fskeletaltheme.neto.com.au%2Fabout_us](url)
=> Added 'position' schema data to Breadcrumb function on all CMS templates

src/css/skeletal-style.css
@jakesergeant found this issue on a child theme, so bringing the fix over. 
`btn-link` is used on product page mobile accordions.
=> btn-link to theme editor styles

src/templates/cart/shopping_cart.template.html
The current paypal implementation should be wrapped in an iife and should be aligned with the same implementation as on the checkout. 
This implementation allows better control on how Paypal is implemented across the board for all merchant webstores, and if the API changes, then we have a way to update existing sites without editing the merchant's templates. There isn't really a use case for the merchant wanting control over this as there isn't much that can change with this:
- https://developer.paypal.com/docs/classic/express-checkout/in-context/javascript_advanced_settings/#setup
But if merchants want more control over how `paypalCheckoutReady` is setup, then they have Skeletal commit history.
**Note: this tag isn't available until 6.41.0** Created as PR so we can get started on …
=> paypal_express_js tag over logic in template

src/templates/cart/shopping_cart.template.html, src/templates/products/includes/shipping_calc.template.html
Fixes issue where error message would be shown before user enters a postcode:
This issue occurs on all sites that don't have a flat-rate shipping method set up.
=> Update no shipping methods logic to check for ship_zip

src/templates/cms/includes/sidebar.template.html
At some point it looks like `rel="nofollow"` was removed from half of the filter links. 
This PR adds it back in.
=> Restore nofollow for filter links

gulpfile.js, package-lock.json, package.json
Removed cssnext in favour for autoprefixer and cssnano.
Slimmed app.css by 90kb
Current app.css
New app.css
=> Updated sass gulptask

src/templates/cart/includes/invoice_body.template.html
The invoice page payment method section will only display a select amount of options because it uses a static if statement to figure out which payment method to display. 
This isn't scaleable for new options (e.g web payments) and also the name doesn't reflect what the merchant has placed in for the pay option (e.g they might have changed direct deposit to something more specific, this new name wouldn't have displayed in the current setup).
=> CAT-1007 updated invoice_body payment methods to be more robust

src/templates/headers/includes/head.template.html
This will add some more blocking ability on cart page and myacct page (deeper account pages are fine because blocked by password login.
Just helps line up with robots file more and with Google info - https://support.google.com/webmasters/answer/6062608?hl=en
=> Added Meta for noindex, nofollow

src/js/custom.js
There is no reference to 'disp_ajax_templ' in either Skeletal or eCommerce, so this event listener should be removed.
This makes the initPageFuncs clearer on its functionality; init add to wishlist, add to cart and site search.
=> Removed disp_ajax_templ event listener

src/templates/headers/includes/head.template.html
Internet Explorer supports the use of a document compatibility `<meta>` tag to specify what version of IE the page should be rendered as. Unless circumstances require otherwise, it's most useful to instruct IE to use the latest supported mode with edge mode.
For more information, [read this awesome Stack Overflow article](https://stackoverflow.com/questions/6771258/what-does-meta-http-equiv-x-ua-compatible-content-ie-edge-do).
=> IE compatibility mode meta tag

gulpfile.js, package-lock.json, package.json
gulp-sass now recommend having a direct dependency of `node-sass`:
- https://www.npmjs.com/package/gulp-sass#install
Without this, it spits out a string of warnings and errors when installing the dependencies. And now it's more explicit with the compiler:
- https://www.npmjs.com/package/gulp-sass#basic-usage
=> node_sass for development

src/templates/customer/edit_account/template.html
I've always been bothered by how disorderly the Dropshipping Information section is. Shout out to Curtis for helping me make it less cluttered.
Old:
New:
=> Cleanup the text in the dropshipping information section

src/templates/customer/resetpwd/template.html
The resetpwd page doesnt have a show_message tag in it. This means any errors (such as "password missing a special character" are not shown to the user.
=> CAT-1566 add show_message tag to the resetpwd account page

src/templates/customer/wholesaleregister/template.html
When content from this text area gets imported into the control panel customer card, it cuts off at 255 characters. Adding `maxlength` will prevent customers from going over this limit.
=> Add maxlength 255 to the custom field textarea

src/templates/customer/wholesaleregister/template.html
Changes:
- Hidden the username field (to be inline with the standard registration form)
- Moved the form labels to sit above the fields instead of inline
- Rearranged some of the form fields 
- Reduced the desktop col width to `col-md-9`
=> Update the page layout and design of the wholesale registration form

src/templates/cart/upsell.template.html
The upsell image isn't responsive so it's overlapping the form fields:
=> Cart upsell make image responsive

src/templates/products/includes/child_products.template.html
For child products that contain extra options, the current logic displays a "See buying Options" button (which does nothing) and disables the quantity field which prevents customers from purchasing the product. 
Example of issue: http://horsup.neto.com.au/dress?nview=country
=> Child products that contain extra options issue
