private/www/netosuite/Templates/skeletal/cart/shopping_cart.template.html
Includes loads of bug fixes, 2015 b@se code & more
=> Complete overhaul of cart page

private/www/netosuite/Templates/skeletal/customer/wholesaleregister/template.html
=> wholesale register error messages

httpdocs/assets/themes/skeletal/css/app.css, httpdocs/assets/themes/skeletal/css/app.less, private/www/netosuite/Templates/skeletal/customer/template.html
Some simple logic fixes for the account page that will stop the "Pay" button and the "Due Date" showing up on the order cards for Cancelled orders
=> Correction of Customer Account page cards for Cancelled Orders

src/templates/customer/nr_track_order/template.html
All of these fields are mandatory but there are no visual queues for this
=> Usability fix to signify mandatory fields

src/templates/cart/onepage.template.html
Updated to current base instead of data tags and also gave direct deposit: 'Direct Deposit' || [@name@] like 'Bank Deposit'
and Master Card 'Master Card' || [@name@] like 'MasterCard'
=> Updated payment_method function

src/templates/thumbs/product/list.template.html
A significant portion of the required flags for structured data were missing, as well as the fix for currency symbols on pricing. 
Minor indenting fixes were also made.
=> Implementing product structured data onto the list.thumbnail + linting

src/templates/customer/edit_account/template.html, src/templates/thumbs/product/list.template.html, src/templates/thumbs/product/template.html
- Removal of the substring() method trimming the postcode field on change
- Adding in `[%if [@min_qty@] > 0%][@min_qty@][%else%]1[%/if%]` conditional logic to allow for the hidden qty input to appreciate minimum order Qty
=> Patching of Edit Account javascript for internation postcodes + min_qty thumbnail logic

src/templates/cart/shopping_cart.template.html
This will need to be tested w/ the old Paypal setup.
=> [INT-2862] Adding in code for the new Paypal button 💰

src/templates/cart/empty.template.html, src/templates/customer/logout.template.html, src/templates/customer/template.html, src/templates/customer/warranty/select_dispute_reason.template.html, src/templates/customer/warranty/template.html, src/templates/customer/wholesaleregister/done.template.html, src/templates/customer/wholesaleregister/template.html, src/templates/customer/write_contentreview/confirm.template.html, src/templates/customer/write_contentreview/not_found.template.html, src/templates/customer/write_review/template.html
Nothing urgent/important, just slight tweaks that will make the wording less awkward in certain places and removing instances of "click here" on buttons in particular for redundancy purposes.
=> Demi button patrol

src/templates/thumbs/product/box.template.html
=> Line breaks between pricing on browsing history

src/templates/cms/default.template.html, src/templates/cms/products.template.html, src/templates/cms/search_results.template.html, src/templates/cms/store_finder.template.html, src/templates/footers/template.html, src/templates/headers/template.html, src/templates/products/includes/header.template.html, src/templates/products/template.html, src/templates/thumbs/content/template.html, src/templates/thumbs/product/list.template.html, src/templates/thumbs/product/template.html
**General:**
-  Site Logo
-  Social Profile Links
-  Breadcrumbs
**Product page and thumbnails:**
-  PriceValidUntil attribute for promotional prices (promo end)
-  Product Brand
**Blog thumbnails and default page:**
-  Headline
-  Author (person schema)
-  description
-  Fix URL on the thumbnail
-  Add publisher (site name)
-  date published
-  logo
=> Skeletal structured data rework

src/templates/cart/shopping_cart.template.html, src/templates/footers/template.html, src/templates/products/includes/header.template.html, src/templates/products/template.html, src/templates/thumbs/product/list.template.html, src/templates/thumbs/product/template.html
To set up Afterpay using the new third-party scripts, you need to set up two distinct third-party scripts.
The first script needs to simply contain the code for the modal:
```
<div class="modal fade" id="afterpayModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
<div class="modal-dialog" role="document">
<div class="modal-content">
<div class="modal-header">
<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
</div>
<div class="modal-body">
<div class="row">
<div class="col-xs-12">
<h5>Pay over 8 weeks and receive your order now!</h5>
<p>Using Afterpay you can pay for your order over [@REFERRAL_KEY2@] weeks. There's no interest or added fees and nothing to pay today. Payment will be automatically taken from …
```
=> New third party script tags

src/templates/customer/wholesaleregister/template.html
Removing sidebar and including bootstrap column grid
=> wholesale reg grid fix

src/templates/cart/shopping_cart.template.html
=> Making the paypal button nicer on the cart page

gulpfile.js
Initial implementation of error handling
=> gulpfile.js modification to check less file is present

src/css/app.css, src/css/app.less, src/templates/cms/category.template.html, src/templates/cms/default.template.html, src/templates/cms/home.template.html, src/templates/cms/products.template.html, src/templates/cms/store_finder.template.html, src/templates/products/template.html
=> Responsive content class helper 🐚

src/templates/cart/invoice.template.html
Show physical address when there is no POaddress.
=> Issue #116 new poaddress logic

src/templates/customer/pay_order/pay_now_confirm.template.html, src/templates/customer/payrec/template.html
This page is now under the codebase for controlled checkout, but it's
nice to have a fix here to reference for change there too.
=> Removed default option to force onchange event 👔

src/templates/products/template.html
Standard feature of Neto missing from generic templates
=> Adding terms to content tabs

src/templates/headers/template.html
Currently the class field on a menu in the cPanel is not included in the design. This probably need to be done in the other menu's too.
=> adding class back into menus

src/templates/cms/store_finder.template.html
=> Added Google Maps API key to other store finder template 📱

src/js/custom.js
I can't think of a reason why seeing the search results of a clicked product would be beneficial.
=> Adjusted search dropdown to link directly to url

src/templates/customer/edit_account/template.html
=> removed block class from save changes btn

src/css/app.css, src/css/app.less, src/templates/footers/template.html
I've also tidied up some of the formatting for the existing icons.
=> ID-1011 Afterpay footer icon support

src/templates/cart/onepage.template.html
19 digit credit cards are a thing now.
=> Remove maxlength attr from CCN field.

src/css/app.css, src/css/app.less
This style will ensure there isn't a gap at the bottom of the page.
=> hid nactivty

src/css/app.css, src/css/app.less, src/templates/footers/template.html
**Do not merge!**
Need to first place my local SVG onto the CDN and then edit the background image in app.less:
- http://devphil.neto.com.au/assets/themes/skeletal-ID-1321/img/paymenticons.svg
=> Added footer icon support for paymark and qcard

src/templates/headers/template.html
I'm not too sure if this is needed, I think the wording Favourites works but we do need to be consistent with this as there are section that says; Re-Order, Reorder and then the templates are favourites
=> Issue #210

src/templates/cart/shopping_cart.template.html, src/templates/footers/template.html, src/templates/headers/checkout.template.html, src/templates/headers/empty.template.html, src/templates/headers/template.html, src/templates/products/includes/header.template.html, src/templates/products/template.html, src/templates/thumbs/product/list.template.html, src/templates/thumbs/product/template.html
This will give us functionality to not load any third party scripts! Just add a spicy query string:
`site.neto.com.au/?disable-scripts=true`
=> Added disable scripts logic

src/templates/cart/invoice.template.html
Increase logic scope for Direct Deposit on invoice template.
=> Broaden logic

src/templates/customer/template.html
=> Fixed #236

src/templates/headers/template.html, src/templates/products/includes/buying_options.template.html, src/templates/products/includes/header.template.html, src/templates/products/template.html, src/templates/thumbs/product/list.template.html, src/templates/thumbs/product/template.html
=> Structure Data Update

src/templates/cms/home.template.html, src/templates/footers/template.html
After merging lots of PR there were a couple issues that didn't get resolved correctly.
=> Merge conflicts

src/templates/headers/template.html
=> Added space infront css_class

src/templates/customer/edit_account/template.html
Not sure if this error message is ever hit, but the email should be updated to reflect the company email address. 
Also it should match the following line from another template:
https://github.com/Naraceaus/Skeletal/blob/master/src/templates/customer/edit_address/template.html#L242
=> Updated error message email address

src/templates/products/includes/components.template.html
=> Fix issue #297

src/templates/cart/invoice.template.html
=> div.row didn't have closing tag

src/templates/cart/invoice.template.html, src/templates/cart/rental_invoice.template.html, src/templates/cms/store_finder.template.html, src/templates/customer/mystore/edit.template.html, src/templates/customer/nr_track_order/order.template.html, src/templates/customer/track_order/order.template.html, src/templates/customer/warranty/open_dispute.template.html, src/templates/footers/checkout.template.html, src/templates/footers/template.html, src/templates/products/includes/images.template.html
=> Added rel attribute to external links

src/templates/customer/template.html
- Wishlist label link
- Consistency in pagination design
- default label style
=> Small fixes

src/templates/cart/invoice.template.html, src/templates/cart/onepage.template.html, src/templates/cart/rental_invoice.template.html, src/templates/footers/checkout.template.html
Finished #140, a few templates look to have been missed.
=> Updated tracking codes that were missed

src/templates/products/includes/components.template.html
There was two fixed_assemble attributes on this particular input
=> Removed duplicated fixed_assemble on input

.buildkite/pipeline.yml, .buildkite/upload.yml, README.md
With this skeletal will update in the theme store again when changes occur to master :confetti_ball:
=> Updated pipeline file to work with new buildkite

README.md
- Updated Neto FTP docs link 
- Updated Neto developer docs link 
- Updated Bootstrap link to point to version 3.3
- Updated cPanel theme editor path
=> Updated some links in readme

src/templates/customer/login.template.html, src/templates/customer/register/template.html
#271 
- Still need to review the wholesale register form
=> Added required fields to login/register

src/templates/customer/wholesaleregister/template.html
Also formatted the `[%extra_customer_fields%]` function block to match the style guide and added required attributes to existing required fields. 
#271
=> Added [@required_field@] logic to wholesale registration form

src/templates/products/includes/header.template.html
=> Updated availability schema on product header template

src/css/app.css, src/css/app.less
=> Remove styling of p:first-child within product description

src/templates/cart/invoice.template.html
=> Fix spelling mistak

src/templates/cart/shopping_cart.template.html
=>  Added two decimal points to discount percent to fix issue where it is rounded up

src/templates/products/includes/components.template.html
The current logic `[%if [@itm_price@] %]` does not allow the kit component price to be displayed as $0. The logic will be false and display the store price.
=> fixed kit component price logic

README.md
Updated readme for forks @matt-downs  :)
This is a local git setup so you have access to all current PR's.
=> Forking skeletal

src/css/app.css, src/css/less/_neto.less
=>  Added text-align: right to savings container

src/templates/customer/nr_view_order/order.template.html, src/templates/customer/nr_view_order/quote.template.html, src/templates/customer/view_order/order.template.html, src/templates/customer/view_order/quote.template.html
- Only show pay now button on view order screen if there is an amount owed #338
- Fix issue where pay now button would be displayed once for each orderline in nr view order
- Duplicate view order template to nr view order template to remove legacy code
- Duplicate view quote template to nr view quote template to remove legacy code
=> Revamp view order and quote pages

src/templates/products/includes/buying_options.template.html
=> Hide product page shipping calculator for service items

src/templates/customer/approve_quote/template.html
=> Fix spelling mistake

src/templates/customer/write_contentreview/confirm.template.html, src/templates/customer/write_contentreview/not_found.template.html, src/templates/customer/write_review/not_found.template.html, src/templates/customer/write_review/preview.template.html, src/templates/customer/write_review/template.html, src/templates/customer/write_review/write.template.html
- Fixed issue where customername field would not be submitted if review was posted by logged in user (#285)
- Removed some unused javascript code 
- Tweaked styling of buttons and added fa icons to better match the rest of the theme
=> Review forms changes 

src/templates/customer/login.template.html, src/templates/customer/register/template.html
- Added required attribute to required login/register fields
- Removed some redundant value tags from login/register fields
...sorry I can't create a branch on the main repo yet 😨
=> Added required attribute to required login/register fields

src/templates/customer/template.html
- Changed it's markup to use `h3` for the title like the other buttons
- Cleaned up the HTML for some of the other buttons
=> Approve quote button wants to be noticed 

src/templates/customer/forgotpwd/template.html, src/templates/customer/mystore/view.template.html, src/templates/customer/standing_orders/template.html, src/templates/customer/write_contentreview/preview.template.html
alert-error isn't a bootstrap class.
Issue #339
alert-danger is.
=> Fixed css to use correct classes

src/css/app.css, src/css/app.less, src/css/less/_neto.less
Fix for #272.
Someone please **test thoroughly**. AFAIK everything looks like it works but I don't want to be responsible for breaking the cart button on Skeletal.
=> Decrease z-index on cart button

src/templates/customer/warranty/dispute_updated.template.html
Unncessary '>' on line 11 after 'class="btn btn-default"' resulting in broken code.
=> Removed '>' on line 11

src/templates/products/includes/images.template.html
=> Removed meta image tag

src/templates/customer/edit_account/template.html
=> Added newsletter unsubscribe to edit account page

src/templates/cart/shopping_cart.template.html
Refer to issue #400
Also fixed spacing between **GST Inc.**
=> Add surcharge row to cart pricing information

src/templates/cart/invoice.template.html, src/templates/cart/rental_invoice.template.html, src/templates/customer/approve_quote/accept_quote_confirm.template.html, src/templates/customer/approve_quote/delete_quote_confirm.template.html, src/templates/customer/approve_quote/template.html
=> Broken functionality on email address contains '+' character

src/templates/cart/shopping_cart.template.html
=> Add margin to bottom of payment plans card on cart page 

src/templates/customer/write_contentreview/confirm.template.html
=> Remove duplicate home button on content review success page

src/templates/cart/invoice.template.html, src/templates/cart/quote_invoice.template.html, src/templates/cart/rental_invoice.template.html
=> Added test id to invoice page

src/templates/customer/write_review/write.template.html
Also remove `size` attribute as this is ignored - `.form-control` fields are 100% width
=> Make the required review fields actually required

package-lock.json
Found 12 vulnerabilities (10 moderate, 2 high) in 6676 scanned packages
Found 1 high severity vulnerability in 6641 scanned packages
---
Working through how to deal with jquery internally first.
=> fixed majority of package security issues

src/templates/headers/includes/head.template.html
Type reference - https://developers.facebook.com/docs/reference/opengraph#object-type
Debugger - https://developers.facebook.com/tools/debug/
=> OG:type to be conditional

src/js/custom.js, src/templates/cart/adduserlogo.template.html, src/templates/cart/includes/cart_items.template.html, src/templates/cart/includes/invoice_body.template.html, src/templates/customer/mystore/edit.template.html, src/templates/customer/track_order/order.template.html, src/templates/headers/template.html, src/templates/products/includes/child_products.template.html, src/templates/products/includes/components.template.html, src/templates/products/includes/product_information.template.html, src/templates/products/includes/product_scripts.template.html
=> Convert spaces to tabs for consistency with other templates

src/templates/headers/includes/head.template.html
How to verify site ownership - https://support.google.com/webmasters/answer/35179?hl=en
Test - https://search.google.com/search-console/welcome
=> Google verification into meta tag

src/templates/customer/edit_account/template.html, src/templates/customer/edit_address/template.html, src/templates/customer/wholesaleregister/template.html
- Toggled 'Zip code/ postal code' label,
- Made required `*` consistent on account pages,
- Only show ABN field for Australian merchants.
=> Account pages i18n

src/templates/products/includes/images.template.html
The old image looks pretty outdated, 
and it's not vertically centered, 
and we already load font awesome so no need for another asset.
=> changed pdf image for FA icon

gulpfile.js, package-lock.json, package.json
Added plumber for better error handling
- https://www.npmjs.com/package/gulp-plumber
This is a good article as to why plumber is good:
- https://gist.github.com/floatdrop/8269868
=> Gulp error handling

src/css/skeletal-style.css
Bootstrap button SASS - https://github.com/twbs/bootstrap/blob/v4-dev/scss/_buttons.scss#L11-L46
=> Theme editor button styles to be more aligned with bootstrap styles

src/templates/cms/default.template.html
Found a duplicate class in this template.
Also; is it worth removing Google+ from the share dropdown?
=> Duplicate Class

src/templates/products/includes/child_products.template.html
=> Implement specific_autohide

src/templates/customer/login.template.html, src/templates/customer/register/template.html, src/templates/customer/wholesaleregister/template.html
> That tag is now useless. it was fairly useless when it was a thing. `[%submit_token%]` can be removed if you see it
=> removed submit_token references

src/templates/footers/checkout.template.html, src/templates/footers/template.html
Will have a positive SEO impact.
=> Added nofollow to platform branding link.

src/templates/cms/store_finder.template.html, src/templates/stockists/template.html
This PR patches the BS3 branch with the changes made in [PR-505](https://github.com/NetoECommerce/Skeletal/pull/505).
=> Added GOOGLE_GEO_API logic to stockists in BS3

src/templates/customer/resetpwd/template.html
Same change was added to master branch in PR #515
=> Add show_message tag to resetpwd template

src/templates/cms/includes/sidebar.template.html
Add class to product filter titles so they can easily be targeted when styling
=> Add class to product filter titles

src/templates/cms/default.template.html
- Remove Google+ from the share dropdown 
- Remove redundant "/" in button that has been bugging me since I started
=> Remove Google+ from the share dropdown

src/templates/cms/includes/sidebar.template.html
Add an if selected tag around the price filter "clear" button so this button will only display when filtered by price
=> Price filter clear button

src/templates/products/includes/buying_options.template.html
- Fix up the alignment of B@SE tags for consistency 
- Add comment notes for each section for better structure
=> Fix buying options template tag alignment

src/templates/products/includes/child_products.template.html
- Fix up the alignment of B@SE tags and code for consistency
- Add comment notes for each section for better structure
=> Fix child product template code alignment

src/templates/customer/login.template.html, src/templates/customer/register/template.html
- Replace `card-body` for `card-header` for the card headers
- Clean up the wording for consistency
- Tidy up the template - padding, font-weights etc
=> Tidy login/register templates

src/templates/products/includes/images.template.html
- Add bottom padding to alt images
- Remove the `<br>` tag and add bottom padding to the main image div instead
=> Add padding to product images

src/templates/products/includes/header.template.html, src/templates/thumbs/content/template.html
Google+ has been deprecated so removing this from our share dropdown
=> Remove google plus

src/templates/products/includes/buying_options.template.html, src/templates/products/includes/header.template.html, src/templates/products/includes/product_information.template.html, src/templates/products/template.html
**Changes can be seen on the following staging theme: https://skeletaltheme.neto.com.au/sample-product-5?nview=2020-08-skeletal**
Included the `product_information.template.html` within the product schema data wrapper to fix the review issue.
- Review schema issue: https://search.google.com/structured-data/testing-tool/u/0/#url=http%3A%2F%2Fskeletaltheme.neto.com.au%2Fsample-product-2
- With the fix: https://search.google.com/structured-data/testing-tool/u/0/#url=http%3A%2F%2Fskeletaltheme.neto.com.au%2Fsample-product-2%3Fnview%3D2020-08-skeletal
- Also added schema data URL and SKU field.
Minor styling changes:
- Removed SKU from the bottom of the product description
- Cleaned up of the main product template - comments, `rows` and `cols`
- Cleaned up the upsell etc products
=> Schema data product review fix

src/templates/customer/template.html, src/templates/customer/wholesaleregister/done.template.html
- Add register tracking code to the standard my account template and to the wholesale registration done template.
- Update the wholesale `done.template.html` to display the user's name rather than the username value.
=> Add register tracking code

src/templates/customer/edit_address/template.html
**Fixed the following:**
- "Delete Address" and "Save Address" buttons on tablet view
- Fix label `for=""`
- Spelling
- Indentation
=> Fix responsive edit address buttons

src/templates/customer/edit_account/template.html
Customer details are saving correctly
=> IMP-571 fix done

src/templates/customer/edit_account/template.html
=> IMP-571 feedback changes

src/templates/customer/warranty/open_dispute.template.html
The [@model@] and [@extra@] tags are wrapped around [%ESCAPE%][%/ESCAPE%]
=> added escape tag to fix the XSS issue
